### ISSUE TITLE
cant compile avr-libc

### ISSUE THREAD

**Issue by bidinzky** [avr-rust/libc#3]
Hello,

first thanks a lot for the fast implementation 👍 , but when i try to compile it i get an error.
Maybe it can help you to improve this any further.
[log.txt](https://github.com/avr-rust/libc/files/1535786/log.txt)

**Comment by dylanmckay** [comment]
I think this may be a bug with avr-gcc on your system

A bunch of people have had this same issue when trying to compile avr-libc normally.

* https://lists.nongnu.org/archive/html/avr-libc-dev/2010-04/msg00075.html
* http://www.avrfreaks.net/forum/avr-libc-200-not-compiling-error-gcrt1o-fialed
* http://avr.2057.n7.nabble.com/Patch-avr-Shrink-interrupt-vector-table-down-to-last-used-entry-td19487.html

Can you please post the output of

```bash
avr-gcc --version
avr-ld --version
```

**Comment by bidinzky** [comment]
root@phoenix:/home/lukas# avr-gcc --version
avr-gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@phoenix:/home/lukas# avr-ld --version
GNU ld (GNU Binutils) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

**Comment by dylanmckay** [comment]
I cannot reproduce this on my own machine, although I am an a much, much more recent version of GCC.

I have a hunch that this commit I just pushed may fix it fee18d845.
